spring:
  application:
    name: trazabilidad-autogestion
  jpa:
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          batch_size: 5
        default_schema: public
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 100
      minimum-idle: 10    
  kafka:
    bootstrap-servers: cap-sg-prd-1.securegateway.appdomain.cloud:18007
    
app:
  topic:
    foo: queue-notification-tickets
  oauth:
    url: https://api.us-east.apiconnect.ibmcloud.com/telefonica-del-peru-development/ter/public/oauth2/token
    client: afc1075e-69a4-40dc-809a-11e498cea9af
  ticket:
    create: https://api.us-east.apiconnect.ibmcloud.com/telefonica-del-peru-development/ter/triagefcr/createticket/tickets
    retrieve: https://api.us-east.apiconnect.ibmcloud.com/telefonica-del-peru-development/ter/triagefcr/retrieveticket/tickets/
    client: afc1075e-69a4-40dc-809a-11e498cea9af
logging:
  level:
    com.tdp.ms.autogestion: DEBUG