server:
  compression:
    enabled: true
    mime-types:
    - application/json
    - application/xml
  servlet:
    context-path: /autogestion
  port: 8080

spring:
  datasource:
    generate-unique-name: true
  jmx:
    default-domain: jmx_${random.long}
    unique-names: true
  profiles:
    active:
    - traza_dev