package com.tdp.ms.autogestion.model;

public enum TicketStatus {

	CREATED, IN_PROGRESS, RESET, RESET_SOLVED, SOLVED, WHATSAPP, FAULT, GENERIC, WA_SOLVED, FAULT_SOLVED,
	GENERIC_SOLVED, FAULT_TRAZA, WA_DEFAULT, REFRESH, REFRESH_SOLVED, WA_DEFAULT_SOLVED
}
